Explicitly export include/linux/msm_kgsl.h to prevent build error
On a clean build the header is called for before kernel.mk has ran
and thus it can not find the needed header.
hardware/qcom/media/libc2dcolorconvert/C2DColorConverter.cpp:37:28:
fatal error: linux/msm_kgsl.h: No such file or directory
compilation terminated.

Change-Id: I2f4e2fa61c413af07f02ddfb0116a2eb58946445
Signed-off-by: NoelMacwan <yulespencer@gmail.com>